# Setup
title:               ssb2ss
tagline:             'Sungmok Hong'
description:         '20213099'
url:                 http://ssb2ss.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              ssb2ss
  url:               https://ssb2ss.github.io
  email:             ssb2ss@kookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
